[package]
name = "rchaty-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.79"
tracing = "0.1.40"
keycloak = "21.0.102"
dotenvy = "0.15"
reqwest = "0.11.27"
